baseURL = 'https://example.org/'
languageCode = 'pt-br'
title = '8enrich'
theme = 'risotto'

sectionPagesMenu = "main"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  contact_message = "Se quiser conversar comigo sobre algo que achou interessante, me mande um e-mail: <a href='mailto:8enrich.blog@gmail.com'>8enrich.blog@gmail.com</a>"
